### ISSUE TITLE
Single image load event + progress event

### ISSUE THREAD

**Issue by Mteuahasan** [m5kr1pka/canvas-scroll-clip#15]
Hi there,

For a project, I needed two new events :

**1 -Single image load**

So that it is easy to create an incremental loader (might be already something that handles this case?)

**2 - Progress event**

With the frame number as parameter. I need to make things appear and disappear at specific frames. Having the frame number as an argument is easier than dealing with the `scrollTop` value.

If you want to implement it, I can submit a PR (or you can do it in about 5 minutes).

Thanks ! 👋

**Comment by m5kr1pka** [comment]
👍  create a pull request

`Note: commits should conventional commits tagging, meaning feat(core): commit msg`

**Comment by Mteuahasan** [comment]
Hi, I cannot create a new branch yet

**Comment by m5kr1pka** [comment]
Make a fork and then pull request the changes.
