### ISSUE TITLE
Looks like three different containers overlapping each other instead of one smooth animation

### ISSUE THREAD

**Issue by Manas-maker** [m5kr1pka/canvas-scroll-clip#18]
I was trying to implement this in a react page by calling it inside an effect, this is how it ended up looking, the animation ends halfway in the first container and then continues in the second container while the first container remains stuck, you get more distinct containers as you increase the scrollarea
![image](https://user-images.githubusercontent.com/64654573/197373295-cc0d3c36-12ee-4c2e-8cb8-bab1160a0028.png)

**Comment by m5kr1pka** [comment]
Created a new release, which should fix this issue. Here is a gist with React Component, pretty straight forward implementation: https://gist.github.com/m5kr1pka/f02c2afcaf5c73cc38546a801c48368a

**Comment by Manas-maker** [comment]
![image](https://user-images.githubusercontent.com/64654573/197751498-10304cad-2c9f-42de-b0bc-1a9b01761e8d.png)
the issue's still here, just copied your implementation

**Comment by m5kr1pka** [comment]
Make sure it is latest release - 1.3.0, Could you provide working example?

**Comment by Manas-maker** [comment]
It is on 1.3.0 and [here's the entire project directory](https://github.com/Manas-maker/canvas-scroll-react/blob/main/src/App.js). This canvas is the only element on the page.

**Comment by m5kr1pka** [comment]
@Manas-maker Found where was issue, it was due to React rehydration, library initialised multiple times, made a fix. Released a new version and made minor adjustments for the picture to fill window.
