### ISSUE TITLE
Custom format of builds

### ISSUE THREAD

**Issue by JoiGud** [m5kr1pka/canvas-scroll-clip#23]
Hi and thanks for your package! (Saved me quite some time)

Using it in a standard NextJS/Prismic setup and saw/found out that I needed to change the format flag in the `package.json` `build-all` part to `cjs`:
`"esbuild-esm": "esbuild src/main.ts --format=cjs --target=es6 --bundle --sourcemap=external --outfile=dist/esbuild/main.esm.js",`

Not sure what's the best course of action, as in if it's possible to pick up the required format automatically from the project that's using this package 🤷 

Anyway, just though I'd let you know 😄

**Comment by m5kr1pka** [comment]
you can do, `const CanvasScrollClip = require('canvas-scroll-clip').default`, should work. Decided to stick with esm setup as it had broader usage, at least that what my research showed when I was building the package.

The best case scenario would be an UMD, but esbuild doesn't support that.
