### ISSUE TITLE
Avif support

### ISSUE THREAD

**Issue by koty10** [m5kr1pka/canvas-scroll-clip#34]
Hi, I tried to use .avif images, as they are way more memory-effective than png or webp, but I got this error. 

uncaught canvasscrollcliperror: image with extension ['avif'] is not supported.

Would it be difficult to add support for the avif format? Would adding it to this list of supported formats be enough?

https://github.com/m5kr1pka/canvas-scroll-clip/blob/1c5394864fe396f13dfd1fee03cc2cd062c1cdb4/src/helpers/utils.ts#L191

**Comment by m5kr1pka** [comment]
Could you do a pull request?

**Comment by m5kr1pka** [comment]
Merged.

**Comment by m5kr1pka** [comment]
Added to release - 1.3.2
