### ISSUE TITLE
Use on webpage

### ISSUE THREAD

**Issue by benjibee** [m5kr1pka/canvas-scroll-clip#7]
I've spent weeks attempting to make my own version of exactly this but it's still riddled with bugs and just not working well across browsers, on mobile, etc. So I was very happy to find your library, it's exactly what I need!

The only issue is I'm building a webpage for a client, and there's currently no way to use this library on a webpage (from what I can see after a few attempts). Do you plan on adding support for this anytime soon?

**Comment by m5kr1pka** [comment]
Add type="module" to <script> tag, it should work.
